### PR TITLE
GP-1592: aws celeb configuration

### PR DESCRIPTION
**Pull request by jasonhancock**
https://graymeta.atlassian.net/browse/GP-1592

/cc @jdtobe

### CODE REVIEW

**Comment by jasonhancock** [comment]
now `terraform fmt`'ed

**Comment by jasonhancock** [comment]
retest this please

**Comment by jasonhancock** [comment]
I set up a Jenkins job to run `make test` which runs the `terraform fmt` step and report any failures...so now everything will have to be `terraform fmt`'ed going forward.

**Comment by jasonsattler** [comment]
I see that.  Thank you.

**Pull request merged**
